### ISSUE TITLE
Crash when I was not careful with stageOrder numbering

### ISSUE THREAD

**Issue by JanKn** [NikitaKozlov/Pury#26]
Hi!
I have tested the profiling with our app as we spoke about it on droidconUK, it seems useful especially for people, who don't want to dig in systrace too much. However I've found an issue which causes a crash when I had few method profiling annotations in one class with nested method calls. I have attached my setup and stacktrace.

`@MethodProfiling(profilerName = "Article open", runsCounter = 3, stageName = "setParagraph", stageOrder = 4)
public void method1()...`
 
`@MethodProfiling(profilerName = "Article open", runsCounter = 3, stageName = "createSpannableTexts", stageOrder = 5)
public void method2()...  // this one is called from method1`

`11-01 02:08:34.422 6696-6696/com.dailymail.online.debug E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.dailymail.online.debug, PID: 6696
java.lang.IndexOutOfBoundsException
 at java.util.Collections$EmptyList.get(Collections.java:102)
 at com.nikitakozlov.pury.profile.ProfileResultProcessor.transpose(ProfileResultProcessor.java:67)
 at com.nikitakozlov.pury.profile.ProfileResultProcessor.getAverageProfileResults(ProfileResultProcessor.java:89)
 at com.nikitakozlov.pury.profile.ProfileResultProcessor.takeAverage(ProfileResultProcessor.java:58)
 at com.nikitakozlov.pury.profile.ProfileResultProcessor.process(ProfileResultProcessor.java:27)
 at com.nikitakozlov.pury.profile.Profiler.logIfFinished(Profiler.java:94)
 at com.nikitakozlov.pury.profile.Profiler.stopStage(Profiler.java:78)
 at com.nikitakozlov.pury.aspects.StopProfilingAspect.weaveJoinPoint(StopProfilingAspect.java:60)
 at com.dailymail.online.modules.article.views.ArticleItemHtmlView.onDraw(ArticleItemHtmlView.java:227)
  `

**Comment by NikitaKozlov** [comment]
Fixed
